name: Flow

on:
  push:
    branches:
      - main
      - release/v*

concurrency:
  group: flow-${{ github.ref }}
  cancel-in-progress: true

jobs:
  compile:
    uses: ./.github/workflows/template-compile.yml
    secrets: inherit

  release:
    needs: compile
    uses: ./.github/workflows/template-release.yml
    with:
      artifact-name: ${{ needs.compile.outputs.artifact-name }}
    secrets: inherit
