name: Stable

on:
  push:
    tags:
      - v*

concurrency:
  group: stable-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    uses: ./.github/workflows/template-publish.yml
    with:
      release_tag: ${{ github.ref_name }}
      prerelease: false
    secrets: inherit
